### ISSUE TITLE
Reading/writing text files as string

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#10]
Those two classic functions I copy-pasted who knows how many times (except with updated buffer check):
```gml
/// @function file_read_all_text(filename)
/// @description Reads entire content of a given file as a string, or returns undefined if the file doesn't exist.
/// @param {String} filename        The path of the file to read the content of.
function file_read_all_text(_filename) {
    var _buffer = buffer_load(_filename);
    if (buffer_exists(_buffer))
        return undefined;
    
    var _result = buffer_read(_buffer, buffer_string);
    buffer_delete(_buffer);
    return _result;
}

/// @function file_write_all_text(filename,content)
/// @description Creates or overwrites a given file with the given string content.
/// @param {String} filename        The path of the file to create/overwrite.
/// @param {String} content         The content to create/overwrite the file with.
function file_write_all_text(_filename, _content) {
    var _buffer = buffer_create(string_length(_content), buffer_grow, 1);
    buffer_write(_buffer, buffer_string, _content);
    buffer_save(_buffer, _filename);
    buffer_delete(_buffer);
}
```

Naming comes from C# [File.ReadAllText](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.readalltext?view=net-7.0) and [File.WriteAllText](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?view=net-7.0), but I'm open to other name suggestions.

Technically, `file_text_read_all` and `file_text_write_all` would be more in line with `file_text_*` functions, but I wonder if it wouldn't be misleading, considering that most `file_text_*` functions require the text file handle, while the proposed functions are completely independent from `file_text_*` way of doing things. :thinking:

Could be used for JSON saving/loading as well, vide: https://github.com/Alphish/gm-community-toolbox/issues/9

**Comment by dicksonlaw583** [comment]
If you go ahead with this, I would suggest using exception handling to protect `buffer_load` instead of `file_exists`. Aside from the file not existing, there are other things such as read permissions or conflicting access that can prevent `buffer_load` from working.

```gml
/// @function file_read_all_text(filename)
/// @description Reads entire content of a given file as a string, or returns undefined if the file doesn't exist.
/// @param {String} filename The path of the file to read the content of.
function file_read_all_text(_filename) {
    var _buffer;
    try {    
        _buffer = buffer_load(_filename);
    } catch (ex) {
        return undefined;
    }
    var _result = buffer_read(_buffer, buffer_string);
    buffer_delete(_buffer);
    return _result;
}
```

**Comment by Alphish** [comment]
While this feature didn't gather many upvotes, issue #9 has gathered quite a few, and reading/writing files to entire strings is required for JSON saving/loading.

Thus, I decided to put up this feature for name voting of sorts. There weren't ideas for other names, but maybe someone will come up with some:
- 🚀 for `file_read_all_text()` and `file_write_all_text()` (names inspired by equivalent C# functions, as mentioned above)
- 👀 for something else (please write what other name suggestion you have)
- 😕 for not implementing this function at all, and instead embedding the file string reading/writing in the JSON saving/loading functions

**Comment by Alphish** [comment]
The feature has been accepted for the Community Toolbox.

`file_read_all_text(filename)` should be implemented so that it returns string contents of the file if available, or `undefined` if the load fails for whatever reason. It should be noted that `buffer_load` will return -1 if the file cannot be loaded, so it should be handled by `buffer_exists` check rather than try/catch block; I updated the first post accordingly. `file_write_all_text(filename,content)` should be implemented so that it saves a file with the given string. We will leave detecting and handling potential save failures to the user, as `buffer_save` doesn't seem to provide mechanisms for that out of the box.

`file_read_all_text(...)` tests need to check if the strings are read correctly from some Included Files. I would rather not make tests for `file_write_all_text(...)`, because there's some risk of accidentally making files that would be left over (even if the code is written to delete the unneeded files, something like power outage might interrupt the test or something, leading to messy state).

The demo should include:
- some text area with a string displayed
- a button to change the content of the text area
- a button to replace text area contents with a string read from a user-selected file (via some get open filename async function)
- a button to save text area contents into a user-selected file (via some get save filename async function)

As usual, if someone wants to pick it up for development, please mention it here so that multiple people don't start the same thing independently.

**Comment by Alphish** [comment]
I'm taking this one, hope to get it done soon.

**Comment by Alphish** [comment]
Merged.
