### ISSUE TITLE
Community Toolbox coding conventions

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#11]
Here we can settle on coding conventions for Community Toolbox to apply in the future.

There are a few items to discuss:

# JSDoc comments

For JSDoc comments, I use a triple-slash convention rather than multiline comment convention.

So something like this:
```gml
/// @func some_func()
/// @desc Some function.
/// @returns {Boolean}
```
Rather than this:
```gml
/**
 * @func some_func()
 * @desc Some function.
 * @returns {Boolean}
 */
```

Typically, I would use the following JSDoc annotations: `@func`, `@desc`, `@arg`, `@returns`
The last of these is more of a habit, wouldn't mind using `@return` to make it consistent with other short forms.
If a function doesn't return anything, we might omit `@return` annotation altogether.

Considering the toolbox functions should be reasonably free from additional context, there should be no need for `@context`/`@self` annotation.

In the `@func` annotation, I'd generally keep arguments all lowercase (without word separation) and separated by comma without any space inbetween. So something like `@func relerp(oldfrom,oldto,oldvalue,newfrom,newto)` rather than `@func relerp(old_from, old_to, old_value, new_from, new_to)`

In the `@arg` annotation, I specify expected type using PascalCase conventions, so `String` or `Asset.GMObject` rather than `string` or `asset.gmobject`. The name of the argument is the same as in the `@func` annotation.

In the `@returns` annotation, I specify type using PascalCase just like in the arguments.

# Naming conventions

## Toolbox functions

For the sake of consistency with the rest of GML, I'll be using `snake_case` for these.

## Function parameters and local variables

For my projects, I'd use local variables prepended with underscore, to avoid collisions with keywords and instance/struct variables. So something like `_some_variable`

One side effect is that function parameters - which use non-underscored names in JSDoc - would then be liable for GM1042 warning ("Parameter name differs from specified in JSDoc"...). Personally, I have this warning disabled in IDE so that I could use "clean" argument names in the JSDoc while still benefitting from non-collision of local variables vs keywords and instance variables. The warning could still also be disabled for each Toolbox file. But if other people prefer to use non-prefixed local variables, I won't be stubborn about it, either.

(while we're at that, per-project Feather settings when)

## Toolbox scripts

I generally use `utils_ScriptCategory` convention, with "utils_" being my prefix for collections of utility functions (which the Community Toolbox will be entirely comprised of). The following part would be written in PascalCase.
To avoid name collisions with other assets, it might be good to addtiionally specify it's for Community Toolbox, e.g. something like `utils_CommunityToolboxScriptCategory`

## Other assets

I generally use similar convention among the lines of `prefix_AssetName`, with prefix being lowercase and AssetName being PascalCase. I use prefixes pretty liberally - with `ui_` or `ctrl_` or `obj_` for objects, `rm_` or `demo_` for rooms etc. 

If the rest doesn't mind we can keep using this convention, otherwise I won't be stubbornly sticking to it. I admit my naming scheme might be among more unique ones (not even necessarily the prefix_AssetName part but the sheer number of prefixes in use).

## General notes

Functions that perform some action should ideally be phrased like commands. Something like `do_the_thing(...)`, `calculate_some_result(...)` or `make_game(...)`

Functions that perform some checks should ideally be phrased like questions. Something like `is_defined(...)`, `has_items(...)` or `can_move(...)`
Though since we won't be adding constructors here, these kinds of checks might be relatively few.

Function names might use domain specific prefix sometimes, e.g. `file_read_all_text(...)` rather than just `read_all_text()` or `read_all_file_text()`. It's so that functions related to the same domain are easier to find (like `file_*` family).

When a function expands upon some built-in functionality of GameMaker, it should use naming similar to the original domain. E.g. an array-based counterpart to `collision_circle_list` would be called `collision_circle_array`.

Additionally, when making a toolbox function similar to some industry standard, it's worth checking the commonly accepted naming scheme. Since GML borrows lots of naming conventions from JavaScript, JavaScript conventions will take precedence over other languages in case of multiple competing conventions.

Also, some keywords appearing in function names and related expectations:
- `get` - the function will return a result without modifying anything (except maybe local variables to obtain some result)
- `set` - when "set" is understood as an operation rather than a collection of items, the function is expected to change some variable and is unlikely to return a result
- `load` - the function will read something from a file
- `save` - the function will write/overwrite some file with a given content
- `parse` - the function will read some value from a string

**Note:** These aren't very hard rules. Especially mathematical functions might use some shortened yet still clear notation to express their purpose.

# Code Style

## Identations

I use 4 space characters for an indentation level, no tabs. Mostly because different environments present tabs with different size (if I recall, GitHub pull requests show 8-wide tabs by default, not sure if it still applies).

Won't be too stubborn about not adopting a different convention, but it'd be good to stick to one convention here.

## Braces

I generally use something close to [K&R bracing style](https://en.wikipedia.org/wiki/Indentation_style#K&R_style).
Opening code block braces are in the same line as block definition (this applies to functions, too), while closing braces are in their own line, at the same identation level as the original block-starting expression.

So something like this:
```gml
function some_function(_arg1, _arg2, _arg3) {
    var _some_arg = 123;
    if (_arg1 == _arg2) {
        // do some thing
    } else if (_arg1 == _arg3) {
        // do other thing
    } else {
        // do yet another thing
    }
}
```

I might sometimes omit braces in an `if` block, putting the condition in the first line and the body of the `if` in the second line, like so:
```gml
function other_function(_arg1) {
    if (is_undefined(_arg1))
        return undefined;

    // do the rest
}
```

If there's an if-else block, then the braces should be consistently applied or consistently omitted:
```gml
// OK
if (_some_condition)
    return 1;
else if (_other_condition)
    return 2;
else
    return 3;

// Also OK
if (_some_condition) {
    return 1;
} else if (_other_condition) {
    return 2;
} else {
    return 3;
}

// Not OK
if (_some_condition)
    return 1;
else if (_other_condition)
    return 2;
else {
    show_debug_message("Hello, world!");
    return 3;
}
```

Also, two separate `if` blocks (not part of the same if/else ladder) must be at least one line apart:
```gml
// Not OK
if (_some_condition)
    show_debug_message("AAA");
if (_other_condition)
    show_debug_message("BBB");

// OK
if (_some_condition)
    show_debug_message("AAA");

if (_other_condition)
    show_debug_message("BBB");

// Also OK, because it's same if/else ladder
if (_some_condition)
    show_debug_message("AAA");
else if (_other_condition)
    show_debug_message("BBB");
```

I prefer to use braces for loops like `for` and `while`, and also constructs like `try`/`catch` even if there are only one-liners. To give them extra "visual" weight, so to speak. So consistently using braces everywhere might actually be easier than remembering all these fine-grained rules I came up with. ^^'

## Semicolons

Never put semicolon right after a closing brace, whether related to a block like if/for/etc or a method:
```gml
// OK
some_method = function() {
    show_debug_message("Test method");
}

// Not OK
some_method = function() {
    show_debug_message("Test method");
};
```

Always put semicolon after regular statements:
```gml
//OK
show_debug_message("Hello, world!");

// Also OK
var _best_students = array_filter(_students, function(_student) {
    return _student.grade >= 4.5;
});

// Not OK
show_debug_message("Hello, world!")
```

# Closing remarks
I mostly decide how I do things, but I'm open to tweak some things to make the codebase easier to work with for everyone.

Using `snake_case` for function names is one thing I won't compromise on, since that's essential for toolbox functions seamlessly integrating in the built-in functions ecosystem (at least in the current runtime, conventions might completely change with New Runtime:tm:).

Also, I'll stick to the K&R-ish style of bracing (starting brace on the same line as the block starting expression), because it's the kind of thing someone, somewhere will vehemently disagree about, no matter what you choose, and we need to choose something. Also, K&R-ish braces seem to be often used for JavaScript code, which GML becomes more and more similar to.

Also also, keeping them semicolons at the end of statements. Might help avoid some confusion, let alone silent bugs.

Other than that, I'm more or less flexible on other fronts. Feel free to agree with the conventions I outlined, suggest alternatives or ask about code convention matters that I haven't specified here yet.

**Comment by Alphish** [comment]
Another thing to consider: **what kind of exceptions we throw.**

Personally, I would opt for throwing a simple string, as it appears nicely in the error message and the error window still gives enough information about the call stack, but there might be some cases for and against I haven't considered.

I'd like to avoid making a constructor dedicated to exceptions (let alone a bunch of these), if possible, I wouldn't want to go beyond dumb struct literals.

**Comment by Alphish** [comment]
@dicksonlaw583 Please do make a draft, this would help a lot. ^^

I will probably want to add or clarify some things, but I can refer to these once a draft is made.

**Comment by dicksonlaw583** [comment]
The draft is ready: #54

**Comment by Alphish** [comment]
Closing this now, as the basic contribution guidelines are already published. If some changes/clarifications are required, we might make a separate issue for that.
