### ISSUE TITLE
struct_assign (function to assign properties from one struct to another)

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#40]
The function would assign all proprties from the source struct to a destination struct, and then return the destination struct. If multiple source structs are passed, the later sources overwrite overlapping properties of earlier sources. It's inspired by JavaScript's [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) function, and also discussed in issue #14. I made a more specific feature request, because with the previous one it's hard to tell what is actually being upvoted.

The proposed implementation would be like this:
```gml
/// @func struct_assign(destination,...sources)
/// @desc Assigns properties from one or more source structs to a destination struct, and returns the destination struct.
/// @arg {Struct} destination       The struct to assign properties to.
/// @arg {Struct} [...sources]      The source structs to get properties values from.
/// @returns {Struct}
function struct_assign(_destination) {
    if (argument_count < 2)
        throw "At least one source struct must be given.";
    
    var _assign_method = method(_destination, function(_key, _value) {
        self[$ _key] = _value;
    });
    
    for (var i = 1; i < argument_count; i++) {
        struct_foreach(argument[i], _assign_method);
    }
    
    return _destination;
}
```

One thing to consider is whether we want to enforce passing at least one source struct (as shown above) or left the target struct unchanged instead.

Example usage:
```gml
var _s1 = { a: 1, b: 2 };
var _s2 = { b: 3, c: 4, z: 9 };
var _s3 = { c: 5, d: 6 };

// should print struct like { a: 1, b: 3, c: 5, d: 6, z: 9 }
show_debug_message(struct_assign(_s1, _s2, _s3));
```

It can also simplify initialising properties after constructing a struct:
```gml
var _mary = struct_assign(new Character("Mary"), {
    atk: 12,
    def: 6,
    exp: 123
});
```

**Comment by Mercerenies** [comment]
Javascript allows passing no source structs, and it shouldn't be too hard to implement that corner case, so I'd say allow it.

**Comment by Alphish** [comment]
Implemented and merged.
