### ISSUE TITLE
ds_list_create_from_array/ds_list_add_from_array/ds_list_to_array/ds_list_add_to_array

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#45]
I suggest a set of functions for moving data between arrays and DS lists. Roughly inspired by [TurboGML's ds_list_to_array](https://github.com/FoxyOfJungle/TurboGML/tree/main/TurboGML), though I don't perform any deep conversion (of nested lists and maps) there.

The list-to-array conversion would be especially useful for functions like instance_place_list or collision_circle_list.

The functions would be like the following:
```gml
/// @function ds_list_create_from_array(array)
/// @desc Creates a new DS list with items from the given array.
/// @arg {Array} array      The array to get the items from.
/// @returns {Id.DsList}
function ds_list_create_from_array(_array) {
    var _list = ds_list_create();
    ds_list_add_from_array(_list, _array);
    return _list;
}

/// @function ds_list_add_from_array(list,array)
/// @desc Adds items from the given array to the given DS list.
/// @arg {Id.DsList} list       The list to add the items to.
/// @arg {Array} array          The array to get the items from.
function ds_list_add_from_array(_list, _array) {
    var _length = array_length(_array);
    for (var i = 0; i < _length; i++) {
        ds_list_add(_list, _array[i]);
    }
}

/// @function ds_list_to_array(list)
/// @desc Creates a new array with items fro mthe given DS list.
/// @arg {Id.DsList} list       The list to get the items from.
/// @returns {Array}
function ds_list_to_array(_list) {
    var _size = ds_list_size(_list);
    var _array = array_create(_size);
    for (var i = 0; i < _size; i++) {
        _array[i] = _list[| i];
    }
    return _array;
}

/// @function ds_list_add_from_array(list,array)
/// @desc Adds items from the given given DS list to the given array.
/// @arg {Id.DsList} list       The list to get the items from.
/// @arg {Array} array          The array to add the items to.
function ds_list_add_to_array(_list, _array) {
    var _offset = array_length(_array);
    var _size = ds_list_size(_list);
    array_resize(_array, _offset + _size);
    
    for (var i = 0; i < _size; i++) {
        _array[_offset + i] = _list[| i];
    }
}
```
Note: I considered using `array_create_ext(...)` and `array_foreach(...)` for creating array from list and adding items to array, respectively. But ultimately I found that the differences on VM weren't that large compared to `for` loop, and in YYC the `for` loop significantly outperformed the array functions.

**Comment by Alphish** [comment]
With the release 23.4.1 out of the way, I can go back to actual features. This one accumulated enough votes, so as usual, there will be some name voting and if no one particularly opposes, it'll be included in the upcoming release.

As usual:
- please react with 🚀 if you think the suggested names are fine
- please react with 😕 for something else

**Comment by JujuAdams** [comment]
Do people really use ds_list that much?

**Comment by Alphish** [comment]
The functions are accepted for implementation, will take care of these.

**Comment by Alphish** [comment]
PR merged, closing the issue.
