### ISSUE TITLE
instance_position_topmost(x,y,object)

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#46]
A function to find the topmost (i.e. least depth) instance of the given object at the given position. Can be especially useful for mouse-based UI, where the lower depth elements "cover" the higher depth ones. Inspired by similar `instance_top_position` function from [TurboGML](https://github.com/FoxyOfJungle/TurboGML/tree/main/TurboGML).

```gml
/// @func instance_position_topmost(x,y,object)
/// @desc Finds the topmost instance at the given position (i.e. with the lowest depth).
/// @arg {Real} x                                   The x position to check.
/// @arg {Real} y                                   The y position to check.
/// @arg {Asset.GMObject,Constant.All} object       The object to get the instance of.
/// @returns {Id.Instance} 
function instance_position_topmost(_x, _y, _object) {
    var _list = ds_list_create();
    var _count = instance_position_list(_x, _y, _object, _list, false);
    if (_count == 0) {
        ds_list_destroy(_list);
        return noone;
    }
    
    var _result = _list[| 0];
    for (var i = 1; i < _count; i++) {
        var _instance = _list[| i];
        if (_instance.depth < _result.depth)
            _result = _instance;
    }
    
    ds_list_destroy(_list);
    return _result;
}
```

**Comment by Mercerenies** [comment]
I think the function as stated would be useful. But is `depth` still the right abstraction? Can `depth` meaningfully distinguish instances if the game is using Game Maker's new `layer` system? I feel like `instance_position_topmost` should be written to take into account layers instead, maybe falling back on `depth` if needed.

**Comment by Alphish** [comment]
@Mercerenies Actually, layers have their own depth property - you can even see Depth parameter in layer properties, in the Room Editor. So the `depth` built-in variable (which returns the depth of the layer the given instance is on) is already well integrated into GM's layers system.

**Comment by Alphish** [comment]
This function is planned for the upcoming 24.6.0 release. If someone has a better name suggestions, please post them; otherwise, it'll be implemented as `instance_position_topmost`.

**Comment by Alphish** [comment]
After some discussion, I decided the function will be implemented as `instance_position_top`

**Comment by Alphish** [comment]
Implemented and merged, closing.
