### ISSUE TITLE
Move text control from demo into common UI controls

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#50]
FrostyCat aka [dicksonlaw583](https://github.com/dicksonlaw583) noticed that the text control used in JSON and File utilities tests can be moved into the common UI controls. I agree.

The control could be called `ui_TextArea`, to imply its a control the user can interact with (even if it's light years behind a full-fledged text area control), as opposed to `ui_Text` which could also be used to call a simple text display control, for instance.

**Comment by dicksonlaw583** [comment]
The PR is ready: #51 

I will pick up #47 after this is approved, as the demo for that involves text input.

**Comment by Alphish** [comment]
Alright, the PR for common UI controls has been approved and merged. Now the development of `string_to_char_array` (issue #47) is ready to go!

**Comment by Alphish** [comment]
@biyectivo I'd be hesitant to include a UI framework, because these tend to be very comprehensive and come with a learning curve of their own. Emu in particular depends on Scribble, so it would feel like putting an F1 car engine with a special turbo module into what's ultimately meant to be a toy car.

Also, from 2023.8 forward we will get debug views, which might turn out to be sufficient for like 90% of our UI needs. That's the route I'd like to explore after the 23.4 release before continuing with our makeshift UI controls or committing to an external UI framework.

(I did include Verrific as a dependency, but automated testing is more of a pressing need in case of Community Toolbox functions, I feel)
