### ISSUE TITLE
static_init and static_init_in_progress

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#62]
One of the frequent problems in GameMaker is initialising function statics. Sometimes, one might want to define static functions/variables of a given constructor/funciton, but the way GM handles it requires running the function at least once so that statics are set. It leads to workarounds like so:
```gml
function Hero(_name, _class, _hp, _mp) constructor {
    if (is_undefined(_name))
        exit;
    
    name = _name;
    class = _class;
    hp = _hp;
    mp = _mp;
    
    static create_warrior = function(_name) {
        return new Hero(_name, "warrior", 50, 10);
    }
    
    static create_mage = function(_name) {
        return new Hero(_name, "mage", 20, 30);
    }
}

// initialise the static variables
var _static_init = new Hero(undefined, undefined, undefined, undefined);
show_debug_message(Hero.create_warrior("Alice"));
show_debug_message(Hero.create_mage("Bob"));
```

It works most of the time, but sometimes there might be tricky decisions; e.g. when all variables in the constructor can reasonably accept undefined values for a constructed value. Instead, I propose two functions that can reliably set up a function's static variables/functions, by calling the function from a special "static init context". The functions would be defined as such:
```gml
/// @func static_init(func)
/// @desc Runs a given function from the static init context, so that core function logic won't be executed when setting static function variables.
/// @arg {Function} func        The function to initialise the static variables of.
function static_init(_func) {
    static context = { };
    
    method(context, _func)();
    
    if (struct_names_count(context) > 0) {
        throw $"The static init context was changed when initialising statics of {script_get_name(_func)}.\n" +
                $"Use static_init_in_progress() to exit early from the function.";
    }
}

/// @func static_init_in_progress()
/// @desc Checks whether the current logic is processed from the static init context or not. Use it to exit early when initialising static variables.
function static_init_in_progress() {
    return self == static_init.context;
}
```

And they would be used like so:
```gml
function Hero(_name, _class, _hp, _mp) constructor {
    // instead of choosing a variable to check for statics initialisation
    // you can consistently check for static_init_in_progress() result
    // note that this runs from instance context
    // so even if it's at the top of constructor, it will run after all statics are set up
    if (static_init_in_progress())
        exit;
    
    // ...rest of the constructor setup like above, with statics and instance variables alike
}

static_init(Hero);
show_debug_message(Hero.create_warrior("Alice"));
show_debug_message(Hero.create_mage("Bob"));
```

NOTE: It only works properly from 2023.11 forward!
Earlier on, it would glitch when static struct wasn't set up properly due to this bug: https://github.com/YoYoGames/GameMaker-Bugs/issues/2308

**Comment by Alphish** [comment]
Update: after some tinkering, and taking into account upcoming changes to constructors in 2024.11, I change the proposed implementation to this:
```gml
/// @func static_init(func)
/// @desc Runs a given function in order to make its static variables available, then returns that function's static struct.
/// @arg {Function} func        The function to initialise the static variables of.
/// @returns {Struct}
function static_init(_function) {
    static static_init_context = script_execute(function() {
        static_init_in_progress();
        return static_init_in_progress.static_init_context;
    });
    
    var _static_struct = static_get(_function);
    if (struct_names_count(_static_struct) > 0)
        return _static_struct;
    
    with (static_init_context) {
        script_execute(_function);
    }
    
    if (struct_names_count(static_init_context) > 0) {
        throw $"The context has been modified during static initialisation of {script_get_name(_function)}. Prevent any assignments during static initialisation with static_init_in_progress() check.";
    }
    
    return _static_struct;
}

/// @func static_init_in_progress()
/// @desc Checks whether the code runs from the static init context. Use it to exit early from the function's non-static code.
/// @returns {Bool}
function static_init_in_progress() {
    static static_init_context = {};
    return self == static_init_context;
}
```
This should work in 2024.6 and 2024.1100 betas alike, so no need to worry about having to switch the implementation with a later GM release.

**Comment by DragoniteSpam** [comment]
look, not to rain on anyone's parade but if you're doing something where you need a function called "static_init_in_progress," you seriously need to take a step back and think about what you're doing

wanting to be able to treat statics in gm like statics in c# or java is fair enough - i do it too - but if you've reached the point where you need to worry about recursive static initialization, something has already gone horribly wrong

**Comment by Alphish** [comment]
@DragoniteSpam What do you mean by "recursive static initialization"? `static_init_in_progress()` isn't there to deal with any *recursion* whatsoever, but with running the instance-specific constructor logic that depends on parameters.

Consider this example:
```gml
static_init(LevelGrid);
function LevelGrid(_name, _width, _height) constructor {
    static load = function(_filename) {
        // do some JSON loading stuff
    }
    
    if (static_init_in_progress()) exit;

    name = _name;
    width = _width;
    height = _height;
    cells_count = width * height;
    cells = array_create(cells_count, function(i) {
        return new LevelCell(self, i % width, i div width);
    });
}
```

Also, suppose that I want to be able to use `LevelGrid.load(...)` before creating a LevelGrid instance directly, which I think is a reasonable need.

There is no recursion involved here, but there's some instance-specific logic that relies on width and height values. And maybe I could do something like making a dummy `new LevelGrid(undefined, 0, 0)` call or something, but this becomes very case by case basis and I'd need to do parameters calculus every time to figure out how to avoid dummy constructor calls from making things bad for me.

Not to mention I can no longer perform validations like this in the constructor:
```gml
if (is_undefined(_name))
    throw "Anonymous grids not supported.";

if (_width == 0 || _height == 0)
    throw "Don't create dimensionless grids, please!";
```
because I need to reserve at least one "invalid" case for the dummy static-init calls.

Another alternative I've been using was something like this:
```gml
script_execute(LevelGrid);
function LevelGrid(_name, _width, _height) constructor {
    // setup statics
    if (is_instanceof(self, LevelGrid))
        exit;

    // setup instance
}
```
but this is 1) not quite copypastable/macroable and 2) no longer works in 2024.11.

In comparison, `static_init(ConstructorName)` and `if (static_init_in_progress()) exit;` is quite a no-brainer - you could even put the check at the start of the constructor and still get all the statics initialised. And you no longer lose the ability to validate non-dummy instances either.

It's not like there's some wild recursion going on that is necessary to justify `static_init_in_progress` existence, the cases where a guard like this is needed are pretty common.

**Comment by DragoniteSpam** [comment]
okay, I was thinking something more along the lines of dealing with static initializations that are self-referential, which i've seen people try to do before.

this isn't so bad, carry on

**Comment by Alphish** [comment]
Will go ahead and implement it. Between how broadly I use it, remembering others trying to solve a similar problem and the name collision being extremely unlikely, it hopefully should be fine.

**Comment by Alphish** [comment]
Implemented and merged.

...aaand I've been just today made aware that the "setting up static functions so you can call them without creating a specific instance first" use-case can just as well be covered by prototypal-style assignment like this:
```gml
function ConstructorName() constructor {
  ...
}

ConstructorName.static_member = { ... }
```

Oh well, those who are used to defining statics inside constructor have a tool to handle that now. And also the parent-child relationship between static structs isn't established until the first first instantiation of the child, so there's still use for simplifying static initialisation outside of setting up directly accessible static members.
