### ISSUE TITLE
range_map()

### ISSUE THREAD

**Issue by PhoenixAndStuf** [Alphish/gm-community-toolbox#63]
This is definitely not an original function, but it's so helpful I'm going to put it here for consideration to be added.

It essentially takes a range and a value and calculates what that value would be proportionally in your output range.

```game-maker-language
/// @func range_map(value, range_in_min, range_in_max, range_out_min, range_out_max)
/// @desc Maps a value from an input range (range_in) to an output range (range_out). EX: range_map(5, 0, 10, 500, 1000) would return 750.
/// @arg {real} value           The value from the input range to use.
/// @arg {real} range_in_min    The input range minimum value.
/// @arg {real} range_in_max    The input range maximum value.
/// @arg {real} range_out_min   The output range minimum value.
/// @arg {real} range_out_max   The output range maximum value.
/// @returns {real}

function range_map(value, range_in_min, range_in_max, range_out_min, range_out_max){
	return range_out_min + ((range_out_max - range_out_min) / (range_in_max - range_in_min)) * (value - range_in_min);
}
```

**Comment by Alphish** [comment]
I'm pretty sure basically the same function is already added to the toolbox as `relerp` here:
https://github.com/Alphish/gm-community-toolbox/blob/880d373b7e73040658dc57254350d9a14c18eb81/Community%20Toolbox/scripts/utils_CommunityToolboxMath/utils_CommunityToolboxMath.gml#L111

See also issue #8 for the general discussion.

**Comment by PhoenixAndStuf** [comment]
Whoops, I ought to check next time. Thanks alot!!
