### ISSUE TITLE
string_contains

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#66]
A function to check if a string is contained in another string:
```gml
/// @func string_contains(str,substr)
/// @desc Checks whether a given string contains the given substring or not.
/// @arg {String} str           The string to check.
/// @arg {String} substr        The substring to find in the string.
/// @returns {Bool}
function string_contains(_str, _substr) {
    return string_pos(_substr, _str) > 0;
}
```

**Comment by JujuAdams** [comment]
Would also like to see a variant that accepts multiple substrings and returns `true` if any of them are found in the string.

**Comment by Alphish** [comment]
Going by this feature request, there's at least some demand for such a function: https://github.com/YoYoGames/GameMaker-Bugs/issues/2744

Thus, I'm going to go ahead and implement it.

**Comment by Alphish** [comment]
`string_contains` has been implemented and merged now!
