### ISSUE TITLE
Functional programming stream accessors

### ISSUE THREAD

**Issue by Mercerenies** [Alphish/gm-community-toolbox#7]
The ubiquitous `map`, `filter`, and `reduce`, applied to Game Maker arrays.

```
map(f, array)
filter(p, array)
reduce(f, initial_value, array)
```

I'm not providing sample implementations here, because there's an additional complexity. These functions are most useful with full *closures*, i.e. with the ability for the function argument to use local variables from the enclosing scope. How do we want this toolbox to handle such functions? If GM implements closures, then it's a non-issue at that point. If not (or in the meantime), what I've done in the past is allow these higher-order functions to take any structure with an `invoke` method and then call that, since structures can have state while function objects cannot, in the current version of GM. We could also write these functions such that they detect whether they were given a struct or an ordinary function, with something like

```
if ((is_real(f) || (is_method(f))) {
  // It's a callable GM object
} else {
  // Call .invoke(...) on it
}
```

**Comment by Alphish** [comment]
Aren't these already covered by the [built-in array functions](https://manual.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2FArray_Functions.htm)?
I.e. `array_map`, `array_filter` and `array_reduce`?

**Comment by Mercerenies** [comment]
Hm... I wonder how many Jams I've written custom functions for these without ever checking if they exist. Yes, they are. :P
