### ISSUE TITLE
array_push_ext and array_insert_ext

### ISSUE THREAD

**Issue by Alphish** [Alphish/gm-community-toolbox#71]
Add a function for pushing/inserting contents of entire arrays or their subsets.
Signatures:
```
array_push_ext(array,items,[offset],[length])
array_insert_ext(array,index,items,[offset],[length])
```

`array_push_ext` would likely be a simple `array_copy` call at the end
`array_insert_ext` might involve a resize, a copy of the latter end and then copy of the actual items.

The behaviour of offset/length would be the same as in other Community Toolbox array functions when applicable (e.g. `array_min`/`array_max`), including negative offsets and lengths.

**Comment by tinkerer-red** [comment]
cross post with a FR for GM: https://github.com/YoYoGames/GameMaker-Bugs/issues/6170

here is the code provided as an alternative, which anyone is welcome to use or alter as they see fit obviously.
```gml
function array_insert_ext(array, index, arr_of_val, offset=0, length=max(array_length(arr_of_val)-offset, 0)) {
	static __args = [];
	if (length == 0) return;
	array_resize(__args, length);
	array_copy(__args, 0, arr_of_val, offset, length);
	array_insert(__args, 0, array, index);
	return script_execute_ext(array_insert, __args);
}
```

**Comment by Alphish** [comment]
There are no upvotes here, but there are quite a few on the GM repo feature request, so I think there's a sufficient demand for this one. I'm still open to alternative names suggestion.
