### ISSUE TITLE
File Save/Load

### ISSUE THREAD

**Issue by Kezarus-tech** [Alphish/gm-community-toolbox#87]
A simple and easy way to save files based on this video: https://www.youtube.com/watch?v=l80KenQ0I80

function FileSave(_string, _filename){
	var _buffer = buffer_create(string_byte_length(_string)+1, buffer_fixed, 1);
	buffer_write(_buffer, buffer_string, _string);
	buffer_save(_buffer, _filename);
	buffer_delete(_buffer);
}

function FileLoad(_filename){
	var _buffer = buffer_load(_filename);
	var _string = buffer_read(_buffer, buffer_string);
	
	buffer_delete(_buffer);
	return _string;	
}

**Comment by Alphish** [comment]
They already seem to be a part of the Toolbox (with extra checks) as [file_read_all_text](https://github.com/Alphish/gm-community-toolbox/blob/main/Docs/Reference/Functions/file_read_all_text.md) and [file_write_all_text](https://github.com/Alphish/gm-community-toolbox/blob/main/Docs/Reference/Functions/file_write_all_text.md).

**Comment by Kezarus-tech** [comment]
Then let's close this one.
