### ISSUE TITLE
array_shuffle

### ISSUE THREAD

**Issue by Kezarus-tech** [Alphish/gm-community-toolbox#88]
A simple way to shuffle any array.

```
function array_shuffle(arr){
	var i, j, k;
	var size = array_length(arr);
	for (i = 0; i < size; i += 1){
	    j = irandom_range(i, size - 1);
	    if (i != j){
	        k = arr[i];
	        arr[i] = arr[j];
	        arr[j] = k;
	    }
	}
}
```

**Comment by Alphish** [comment]
Already handled by built-in [array_shuffle](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Farray_shuffle.htm) (returning new array) and [array_shuffle_ext](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Farray_shuffle_ext.htm) (changing the existing array).

These are not in the current LTS, but should make it to the 2025 LTS mainline, and it seems like a good moment for Community Toolbox to get its own LTS-compliant versio. ^^

**Comment by Kezarus-tech** [comment]
Then this should be close.
