### ISSUE TITLE
array_search

### ISSUE THREAD

**Issue by Kezarus-tech** [Alphish/gm-community-toolbox#90]
Sometimes you just need the index of an array and don't want to mess with array_find_index() that needs a lambda.

```
/// @function				array_search(array, value)
/// @description			Search the array for the value and return it's index or -1 if not found
/// @param {Array}			arr     The array to Search
/// @param {Any}			wValue  The value to look for
/// @return {Real}
function array_search(arr, wValue){
	var len = array_length(arr);
	for (var i=0; i<len; ++i) {
	    if(arr[i] == wValue){
			return i;
		}
	}
	
	return -1;
}
```

**Comment by Alphish** [comment]
Seems to be already covered by built-in [array_get_index](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Farray_get_index.htm) (possibly not in LTS).

Other than that, I agree that lambda is quite an overkill, and it seems YYG devs agreed. ^^
(although there was some prodding from the community involved too ;) )

**Comment by Kezarus-tech** [comment]
If it already exists on main then let's close it, shall we?
